version: "3.1"
networks:
  default:
    driver: bridge
services:
#    apache:
#        networks:
#            - default
#        build:
#            context: .
#            dockerfile: ./Dockerfile-apache
#        container_name: vezun-apache
#        volumes:
#            - .:/var/www/html
#    frontend:
#        networks:
#            - default
#        build:
#            context: .
#            dockerfile: ./Dockerfile-frontend
#        container_name: vezun-frontend
#        ports:
#            - "80:80"
#        depends_on:
#            - db
    app:
        networks:
            - default
        build:
            context: .
            dockerfile: ./Dockerfile-app
        container_name: vezun-app

        ports:
            - "80:80"
        volumes:
            - .:/var/www/app
        depends_on:
            - db
    db:
        networks:
            - default
        build:
            context: .
            dockerfile: ./Dockerfile-db
        container_name: vezun-db
        environment:
            - MYSQL_DATABASE=vezun
            - MYSQL_USER=root
            - MYSQL_PASSWORD=123
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_CHARSET=utf8_general_ci